"""Attribute specification and registry for rollout data collection.

Defines which attributes are collected during rollout episodes, their
storage types (for ``TrajectoryDataset`` processing), collation types
(for ``trajectory_collate_fn``), and per-algorithm profiles that select
the appropriate set of attributes.

This module is the single source of truth for attribute metadata.
:mod:`marlite.util.trajectory_dataset` derives its processing lists
from ``ATTR_REGISTRY`` so the two modules stay consistent.
"""

from enum import Enum
from typing import Dict, FrozenSet, List, Optional, Set, Union


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class StorageType(Enum):
    """How the attribute is stored in the raw episode buffer."""
    AS_IS = "as_is"        # Stored as-is (numpy arrays per timestep)
    DICT = "dict"          # Stored as per-agent dicts, converted via np.stack
    EPISODE = "episode"    # Scalar per episode (not per timestep)
    PADDING = "padding"    # Generated by TrajectoryDataset, not from rollout


class CollateType(Enum):
    """How the attribute is handled by ``trajectory_collate_fn``."""
    NUMERIC = "numeric"    # → torch.tensor
    DYNAMIC = "dynamic"    # variable-length → kept as Python list
    OBJ = "obj"            # gym.Space or mixed-type → preserved / special handling
    SKIP = "skip"          # Not processed by the dataset at all


# ---------------------------------------------------------------------------
# Attribute registry — metadata for every known rollout attribute
# ---------------------------------------------------------------------------

ATTR_REGISTRY: Dict[str, Dict] = {
    # --- AS_IS attributes (stored as raw arrays per timestep) ---
    "all_agents_sum_rewards": {"storage": StorageType.AS_IS, "essential": True,  "collate": CollateType.NUMERIC},
    "states":              {"storage": StorageType.AS_IS, "essential": True,  "collate": CollateType.NUMERIC},
    "next_states":         {"storage": StorageType.AS_IS, "essential": True,  "collate": CollateType.NUMERIC},
    "edge_indices":        {"storage": StorageType.AS_IS, "essential": False, "collate": CollateType.DYNAMIC},
    "next_edge_indices":   {"storage": StorageType.AS_IS, "essential": False, "collate": CollateType.DYNAMIC},

    # --- DICT attributes (per-agent dict → np.stack along agent dim) ---
    "alive_mask":          {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "observations":        {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "next_observations":   {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "next_alive_mask":     {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "next_avail_actions":  {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.OBJ},
    "avail_actions":       {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.OBJ},
    "actions":             {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "rewards":             {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "terminations":        {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "truncations":         {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.NUMERIC},
    "infos":               {"storage": StorageType.DICT, "essential": True,  "collate": CollateType.SKIP},
    "all_log_probs":       {"storage": StorageType.DICT, "essential": False, "collate": CollateType.NUMERIC},
    "log_probs":           {"storage": StorageType.DICT, "essential": False, "collate": CollateType.NUMERIC},
    "group_indices":       {"storage": StorageType.DICT, "essential": False, "collate": CollateType.NUMERIC},
    "next_group_indices":  {"storage": StorageType.DICT, "essential": False, "collate": CollateType.NUMERIC},

    # --- Episode-level attributes (scalars set once per episode) ---
    "episode_reward":      {"storage": StorageType.EPISODE, "essential": True,  "collate": CollateType.SKIP},
    "win_tag":             {"storage": StorageType.EPISODE, "essential": True,  "collate": CollateType.SKIP},
    "episode_length":      {"storage": StorageType.EPISODE, "essential": True,  "collate": CollateType.SKIP},
}


# Attributes that are always generated by TrajectoryDataset (not from rollout)
PADDING_ATTRS: List[str] = ["timestep_padding_mask", "next_timestep_padding_mask"]


# SSL-enriched attributes generated by SSLEnrichedTrajectoryDataset subclasses.
# These are NOT in ATTR_REGISTRY because they are never collected during
# rollout — they are added on-the-fly during dataset enrichment.
SSL_ATTRS: List[str] = ["formatted_obs", "construct_padding_mask"]


# ---------------------------------------------------------------------------
# Optional attribute groups
# ---------------------------------------------------------------------------

OPTIONAL_ATTR_GROUPS: Dict[str, Set[str]] = {
    "mappo": {"all_log_probs", "log_probs"},
    "graph": {"edge_indices", "next_edge_indices"},
    "group": {"group_indices", "next_group_indices"},
}


# ---------------------------------------------------------------------------
# Pre-defined rollout profiles
# ---------------------------------------------------------------------------

_ESSENTIAL_ATTRS = [a for a, m in ATTR_REGISTRY.items() if m["essential"]]

ROLLOUT_PROFILES: Dict[str, List[str]] = {
    "full": list(ATTR_REGISTRY.keys()),
    "qmix": _ESSENTIAL_ATTRS,
    "mappo": _ESSENTIAL_ATTRS + list(OPTIONAL_ATTR_GROUPS["mappo"]),
    "graph_qmix": _ESSENTIAL_ATTRS + list(OPTIONAL_ATTR_GROUPS["graph"]),
    "graph_mappo": (_ESSENTIAL_ATTRS
                    + list(OPTIONAL_ATTR_GROUPS["mappo"])
                    + list(OPTIONAL_ATTR_GROUPS["graph"])),
    "group_consensus": _ESSENTIAL_ATTRS + list(OPTIONAL_ATTR_GROUPS["group"]),
    "ssl_group_consensus": _ESSENTIAL_ATTRS + list(OPTIONAL_ATTR_GROUPS["group"]),
    "vae_graph_qmix": _ESSENTIAL_ATTRS + list(OPTIONAL_ATTR_GROUPS["graph"]),
    "msg_aggr_qmix": _ESSENTIAL_ATTRS,
    "g2anet_mappo": (_ESSENTIAL_ATTRS
                     + list(OPTIONAL_ATTR_GROUPS["mappo"])
                     + list(OPTIONAL_ATTR_GROUPS["graph"])),
}


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------

def resolve_required_attrs(
    required_attrs: Union[None, str, List[str], tuple] = None,
) -> List[str]:
    """Normalize *required_attrs* to a flat list of attribute names.

    ``None``
        Returns the **full** profile (all registered attrs) for backward
        compatibility — existing code that does not specify ``required_attrs``
        will collect and process everything exactly as before.

    ``str``
        Looks up the named profile in ``ROLLOUT_PROFILES``.

    ``list[str]`` / ``tuple``
        Validates that every name appears in ``ATTR_REGISTRY`` and returns
        the list unchanged.
    """
    if required_attrs is None:
        return ROLLOUT_PROFILES["full"]

    if isinstance(required_attrs, str):
        if required_attrs not in ROLLOUT_PROFILES:
            raise ValueError(
                f"Unknown rollout profile '{required_attrs}'. "
                f"Available: {list(ROLLOUT_PROFILES.keys())}"
            )
        return ROLLOUT_PROFILES[required_attrs]

    if isinstance(required_attrs, (list, tuple)):
        for attr in required_attrs:
            if attr not in ATTR_REGISTRY:
                raise ValueError(
                    f"Unknown attribute '{attr}' in required_attrs list. "
                    f"Known attributes: {list(ATTR_REGISTRY.keys())}"
                )
        return list(required_attrs)

    raise TypeError(
        f"required_attrs must be None, str, list, or tuple, got {type(required_attrs)}"
    )


# ---------------------------------------------------------------------------
# Filter helpers — used by both rollout and TrajectoryDataset
# ---------------------------------------------------------------------------

def get_timestep_attrs(required_attrs: List[str]) -> List[str]:
    """Return only the per-timestep attributes from *required_attrs*.

    Filters out episode-level and padding attributes.
    """
    return [
        a for a in required_attrs
        if ATTR_REGISTRY[a]["storage"] in (StorageType.AS_IS, StorageType.DICT)
    ]


def get_as_is_attrs(required_attrs: List[str]) -> List[str]:
    """Return AS_IS-type attributes from *required_attrs*."""
    return [
        a for a in required_attrs
        if (ATTR_REGISTRY[a]["storage"] == StorageType.AS_IS
            and ATTR_REGISTRY[a].get("collate") != CollateType.SKIP)
    ]


def get_dict_attrs(required_attrs: List[str]) -> List[str]:
    """Return DICT-type attributes from *required_attrs*."""
    return [
        a for a in required_attrs
        if (ATTR_REGISTRY[a]["storage"] == StorageType.DICT
            and ATTR_REGISTRY[a].get("collate") != CollateType.SKIP)
    ]


def get_numeric_attrs(required_attrs: List[str]) -> List[str]:
    """Return attributes whose collate type is NUMERIC."""
    return [
        a for a in required_attrs
        if ATTR_REGISTRY[a].get("collate") == CollateType.NUMERIC
    ]


def get_dynamic_attrs(required_attrs: List[str]) -> List[str]:
    """Return attributes whose collate type is DYNAMIC (variable-length)."""
    return [
        a for a in required_attrs
        if ATTR_REGISTRY[a].get("collate") == CollateType.DYNAMIC
    ]


def get_obj_attrs(required_attrs: List[str]) -> List[str]:
    """Return attributes whose collate type is OBJ (gym.Space / mixed)."""
    return [
        a for a in required_attrs
        if ATTR_REGISTRY[a].get("collate") == CollateType.OBJ
    ]


# ---------------------------------------------------------------------------
# Derived module-level lists (single source of truth for trajectory_dataset)
# ---------------------------------------------------------------------------

ALL_ATTRS = list(ATTR_REGISTRY.keys())

# --- Dataset processing lists (derived from ATTR_REGISTRY) ---
ARRAY_ATTR_SOURCE = get_as_is_attrs(ALL_ATTRS)
DICT_ATTR_SOURCE = get_dict_attrs(ALL_ATTRS)

# --- Collation lists (derived from ATTR_REGISTRY) ---
NUMERIC_ATTR_SOURCE = get_numeric_attrs(ALL_ATTRS)
DYNAMIC_LEN_ATTR_SOURCE = get_dynamic_attrs(ALL_ATTRS)
OBJ_ATTR_SOURCE = get_obj_attrs(ALL_ATTRS)
