[project]
name = "MARLite"
version = "0.1.0"
description = "A lightweight multi-agent reinforcement learning framework"
license = "BSD-2-Clause"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "torch-geometric>=2.6.1",
    "tqdm>=4.67.1",
    "mpe2",
    "networkx>=3.4.2",
    "pettingzoo[butterfly]>=1.25.0",
    "smac-pettingzoo",
    "magent2",
    "sumo-rl",
    "libsumo",
    "pyvirtualdisplay",
    "numba>=0.63.1",
    "pygame-ce>=2.5.8",
    "cython",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["marlite*"]

[project.scripts]
marlite = "main:main"

[project.optional-dependencies]
develop = [
    "pytest>=8.3.5",
    "pytest-xdist>=3.8.0",
]

cuda = [
    "torch>=2.8.0",
]

rocm = [
    "torch>=2.8.0",
]

mps = [
    "torch>=2.8.0",
]

cpu = [
    "torch>=2.8.0",
]

analysis = [
    "matplotlib>=3.10.3",
    "notebook>=7.4.2",
    "pandas>=2.3.0",
    "scikit-learn",
    "seaborn"
]

[tool.uv]
index-strategy = "unsafe-best-match"
package = true
conflicts = [
    [{ extra = "cuda" }, { extra = "rocm" }],
    [{ extra = "cuda" }, { extra = "mps" }],
    [{ extra = "cuda" }, { extra = "cpu" }],
    [{ extra = "rocm" }, { extra = "mps" }],
    [{ extra = "rocm" }, { extra = "cpu" }],
    [{ extra = "mps" }, { extra = "cpu" }],
]

[tool.uv.sources]
smac-pettingzoo = { git = "https://github.com/CTmH/SMAC-PettingZoo.git" }
magent2 = { git = "https://github.com/CTmH/MAgent2.git" }
dm_env = { git = "https://github.com/CTmH/dm_env.git" }
sumo-rl = { git = "https://github.com/LucasAlegre/sumo-rl.git" }
torch = [
    { index = "pytorch-cu130", extra = "cuda" },
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pypi", extra = "mps" },
    { index = "pytorch-cpu", extra = "cpu" },
]
mpe2 = {git = "https://github.com/Farama-Foundation/MPE2.git"}

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
default = false

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/nightly/rocm7.14"
default = false

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
default = false

[tool.pytest.ini_options]
addopts = "-n auto --import-mode=importlib"
testpaths = ["test"]
