agent_group_config:
  type: "QMIX"
  agent_list:
    agent_0: model1
    agent_1: model1
    agent_2: model1
  model_configs:
    model1:
      feature_extractor:
        model_type: "Identity"
      model:
        model_type: "RNN"
        input_shape: 18
        rnn_hidden_dim: 128
        rnn_layers: 1
        output_shape: 5
  optimizer:
    type: "Adam"
    lr: 0.0005
    weight_decay: 0.0001

env_config:
  module_name: "mpe2"
  env_name: "simple_spread_v3"

epsilon_scheduler:
  type: "logarithmic"
  start_value: 1.0
  end_value: 0.05
  decay_steps: 100

sample_ratio_scheduler:
  type: "linear"
  start_value: 1.0
  end_value: 0.3
  decay_steps: 100

critic_config:
  type: "QMIX"
  state_shape: 54
  input_dim: 15
  qmix_hidden_dim: 128
  hyper_hidden_dim: 64
  feature_extractor:
    model_type: "Identity"
  optimizer:
    type: "Adam"
    lr: 0.0005
    weight_decay: 0.0001

rollout_config:
  manager_type: "multi-process"
  worker_type: "multi-process"
  n_workers: 8
  n_episodes: 1000
  n_eval_episodes: 100
  traj_len: 5
  episode_limit: 500
  device: "cpu"

replaybuffer_config:
  type: "Normal"
  capacity: 50000
  traj_len: 5

trainer_config:
  type: "QMIX"
  gamma: 0.95
  eval_epsilon: 0.01
  workdir: "./results/qmix_default"
  train_device: "cpu"
  eval_device: "cpu"

  train_args:
    epochs: 100
    target_reward: 100
    eval_interval: 1
    batch_size: 128
    learning_times_per_epoch: 1