agent_group_config:
  type: "QMIX"
  agent_list:
    agent_0: model1
    agent_1: model1
    agent_2: model1
  model_configs:
    model1:
      model_type: "RNN"
      input_shape: 18
      rnn_hidden_dim: 128
      rnn_layers: 1
      output_shape: 5
      feature_extractor:
        model_type: "Identity"
  optimizer:
    type: "Adam"
    lr: 0.0005
    weight_decay: 0.0001

env_config:
  module_name: "pettingzoo.mpe"
  env_name: "simple_spread_v3"

epsilon_scheduler:
  type: "logarithmic"
  start_value: 1.0
  end_value: 0.05

sample_ratio_scheduler:
  type: "linear"
  start_value: 1.0
  end_value: 0.3

critic_config:
  type: "QMIX"
  state_shape: 54
  input_dim: 15
  qmix_hidden_dim: 128
  hyper_hidden_dim: 64
  feature_extractor:
    model_type: "Identity"
  optimizer:
    type: "Adam"
    lr: 0.0005
    weight_decay: 0.0001

rolloutworker_config:
  traj_len: 5
  n_workers: 4
  episode_limit: 500
  n_episodes: 1000
  device: "cpu"

replaybuffer_config:
  type: "Normal"
  capacity: 50000
  traj_len: 5

trainer_config:
  gamma: 0.99
  algorithm: "QMIX"
  epochs: 100
  workdir: "./results/qmix_default"
  device: "cpu"
  train_args:
    target_reward: 100
    eval_interval: 1
    batch_size: 128
    learning_times_per_epoch: 1