agent_list:
  - model1
  - model1
  - model2
  - model2

env_config:
  module_name: "pettingzoo.butterfly"
  env_name: "knights_archers_zombies_v10"

model_configs:
  model1:
    model_type: "RNN"
    rnn_hidden_dim: 128
    feature_extractor:
      type: "custom"
      layers:
      - type: Conv2d
          in_channels: 
          out_features: 256
      - type: ReLU
      - type: Linear
          in_features: 256
          out_features: 10
      - type: Softmax
  model2:
    model_type: "RNN"
    rnn_hidden_dim: 128

epsilon_scheduler:
  type: "logarithmic"
  start_value: 1.0
  end_value: 0.05

sample_ratio_scheduler:
  type: "linear"
  start_value: 1.0
  end_value: 0.3

critic_config:
  qmix_hidden_dim: 256
  hyper_hidden_dim: 128

rolloutworker_config:
  traj_len: 5
  n_workers: 4
  episode_limit: 5000
  n_episodes: 1000

buffer_config:
  capacity: 50000

trainer_config:
  gamma: 0.99
  critic_lr: 0.0005
  critic_optimizer: "Adam"
  algorithm: "QMIX"
  epochs: 100
  workdir: "./results/qmix_kaz"
  device: "cpu"
  target_reward: 100
  eval_interval: 1
  batch_size: 256
  learning_times_per_epoch: 1