"""Unit tests for marlite.rollout.attribute_spec."""

import unittest

from marlite.rollout.attribute_spec import (
    ATTR_REGISTRY,
    StorageType,
    CollateType,
    ROLLOUT_PROFILES,
    OPTIONAL_ATTR_GROUPS,
    PADDING_ATTRS,
    ALL_ATTRS,
    resolve_required_attrs,
    get_timestep_attrs,
    get_as_is_attrs,
    get_dict_attrs,
    get_numeric_attrs,
    get_dynamic_attrs,
    get_obj_attrs,
)


class TestStorageType(unittest.TestCase):
    """Verify StorageType enum values and attribute classification."""

    def test_all_attrs_have_known_storage_types(self):
        """Every attribute in ATTR_REGISTRY uses a valid StorageType."""
        valid = {StorageType.AS_IS, StorageType.DICT, StorageType.EPISODE}
        for attr, meta in ATTR_REGISTRY.items():
            self.assertIn(
                meta["storage"], valid,
                f"{attr} has unknown storage type {meta['storage']}",
            )

    def test_essential_attrs_are_timestep_or_episode(self):
        """Essential attrs must be AS_IS, DICT, or EPISODE (not PADDING)."""
        for attr, meta in ATTR_REGISTRY.items():
            if meta["essential"]:
                self.assertIn(
                    meta["storage"],
                    {StorageType.AS_IS, StorageType.DICT, StorageType.EPISODE},
                    f"Essential attr {attr} has invalid storage {meta['storage']}",
                )

    def test_padding_attrs_are_not_in_registry(self):
        """Padding attrs are generated by the dataset, not stored in episodes."""
        for attr_name in PADDING_ATTRS:
            self.assertNotIn(attr_name, ATTR_REGISTRY,
                             f"{attr_name} should not be in ATTR_REGISTRY")


class TestResolveRequiredAttrs(unittest.TestCase):
    """Tests for resolve_required_attrs()."""

    def test_none_returns_full_profile(self):
        """None → full profile (backward compatible)."""
        result = resolve_required_attrs(None)
        self.assertEqual(len(result), len(ATTR_REGISTRY))
        for attr in ATTR_REGISTRY:
            self.assertIn(attr, result)

    def test_str_looks_up_profile(self):
        """A string parameter looks up a named profile."""
        for name in ROLLOUT_PROFILES:
            with self.subTest(profile=name):
                result = resolve_required_attrs(name)
                for attr in result:
                    self.assertIn(attr, ATTR_REGISTRY,
                                  f"{attr} not in ATTR_REGISTRY")

    def test_qmix_profile_is_essential_only(self):
        """QMIX profile contains all essential attrs and no optional ones."""
        result = resolve_required_attrs("qmix")
        essential_count = sum(
            1 for m in ATTR_REGISTRY.values() if m["essential"]
        )
        self.assertEqual(len(result), essential_count)

        optional_union = set()
        for group in OPTIONAL_ATTR_GROUPS.values():
            optional_union.update(group)
        for attr in result:
            self.assertNotIn(attr, optional_union,
                             f"qmix profile includes optional attr {attr}")

    def test_mappo_profile_includes_log_probs(self):
        """MAPPO profile adds all_log_probs and log_probs."""
        result = resolve_required_attrs("mappo")
        self.assertIn("all_log_probs", result)
        self.assertIn("log_probs", result)
        self.assertNotIn("edge_indices", result)

    def test_graph_qmix_profile_includes_edge_indices(self):
        """Graph QMIX profile adds edge_indices and next_edge_indices."""
        result = resolve_required_attrs("graph_qmix")
        self.assertIn("edge_indices", result)
        self.assertIn("next_edge_indices", result)
        self.assertNotIn("all_log_probs", result)
        self.assertNotIn("log_probs", result)

    def test_group_consensus_profile_includes_group_indices(self):
        """Group consensus profile adds group_indices attrs."""
        result = resolve_required_attrs("group_consensus")
        self.assertIn("group_indices", result)
        self.assertIn("next_group_indices", result)
        self.assertNotIn("edge_indices", result)

    def test_all_profiles_contain_essentials(self):
        """Every profile must include all essential attrs."""
        essential_set = {
            a for a, m in ATTR_REGISTRY.items() if m["essential"]
        }
        for name, profile in ROLLOUT_PROFILES.items():
            with self.subTest(profile=name):
                for attr in essential_set:
                    self.assertIn(attr, profile,
                                  f"Profile {name} missing essential {attr}")

    def test_list_is_validated_and_returned(self):
        """A list is validated against ATTR_REGISTRY and returned."""
        result = resolve_required_attrs(["states", "actions", "rewards"])
        self.assertEqual(result, ["states", "actions", "rewards"])

    def test_unknown_name_raises(self):
        """An unknown profile name raises ValueError."""
        with self.assertRaises(ValueError):
            resolve_required_attrs("nonexistent_profile")

    def test_invalid_list_raises(self):
        """A list with an unknown attribute raises ValueError."""
        with self.assertRaises(ValueError):
            resolve_required_attrs(["unknown_attr"])


class TestFilterHelpers(unittest.TestCase):
    """Tests for get_timestep_attrs, get_as_is_attrs, get_dict_attrs."""

    def setUp(self):
        self.full_profile = resolve_required_attrs(None)
        self.qmix_profile = resolve_required_attrs("qmix")

    def test_get_timestep_attrs_excludes_episode(self):
        """timestep attrs should not include EPISODE-type attrs."""
        timestep = get_timestep_attrs(self.qmix_profile)
        for a in timestep:
            self.assertNotEqual(
                ATTR_REGISTRY[a]["storage"], StorageType.EPISODE,
                f"{a} has EPISODE storage but appears in timestep attrs",
            )

    def test_get_as_is_attrs_returns_arrays(self):
        """AS_IS attrs include states, next_states, and optional arrays."""
        as_is = get_as_is_attrs(self.full_profile)
        self.assertIn("states", as_is)
        self.assertIn("next_states", as_is)
        self.assertIn("edge_indices", as_is)
        self.assertIn("next_edge_indices", as_is)
        # states and next_states are essential; edge attrs depend on profile
        as_is_qmix = get_as_is_attrs(self.qmix_profile)
        self.assertEqual(as_is_qmix, ["states", "next_states"])

    def test_get_dict_attrs_returns_correct_count(self):
        """DICT attrs include observations, actions, rewards, etc."""
        dicts_full = get_dict_attrs(self.full_profile)
        dicts_qmix = get_dict_attrs(self.qmix_profile)

        # Full has all dict attrs; QMIX has fewer (no optional)
        self.assertGreater(len(dicts_full), len(dicts_qmix))
        for a in dicts_qmix:
            self.assertEqual(ATTR_REGISTRY[a]["storage"], StorageType.DICT)
            self.assertTrue(ATTR_REGISTRY[a]["essential"])

    def test_timestep_attrs_count_matches_total_minus_episode(self):
        """get_timestep_attrs length equals total attrs minus EPISODE attrs."""
        episode_count = sum(
            1 for a in self.qmix_profile
            if ATTR_REGISTRY[a]["storage"] == StorageType.EPISODE
        )
        self.assertEqual(
            len(get_timestep_attrs(self.qmix_profile)),
            len(self.qmix_profile) - episode_count,
        )


class TestProfileConsistency(unittest.TestCase):
    """Cross-profile consistency checks."""

    def test_no_profile_has_duplicates(self):
        """Every profile must have unique attribute names."""
        for name, profile in ROLLOUT_PROFILES.items():
            with self.subTest(profile=name):
                self.assertEqual(
                    len(profile), len(set(profile)),
                    f"Profile {name} has duplicate attribute names",
                )

    def test_full_profile_has_all_registered_attrs(self):
        """The 'full' profile must contain every ATTR_REGISTRY entry."""
        full = set(ROLLOUT_PROFILES["full"])
        registry = set(ATTR_REGISTRY.keys())
        self.assertEqual(full, registry)


class TestCollateHelpers(unittest.TestCase):
    """Tests for collation-type helper functions."""

    def setUp(self):
        self.full_profile = resolve_required_attrs(None)

    def test_get_numeric_attrs_returns_correct_count(self):
        """NUMERIC attrs include states, alive_mask, observations, etc."""
        numeric = get_numeric_attrs(self.full_profile)
        self.assertIn("states", numeric)
        self.assertIn("next_states", numeric)
        self.assertIn("alive_mask", numeric)
        self.assertIn("observations", numeric)
        self.assertIn("actions", numeric)
        self.assertIn("rewards", numeric)
        self.assertIn("terminations", numeric)
        self.assertIn("truncations", numeric)
        self.assertIn("all_log_probs", numeric)
        self.assertIn("log_probs", numeric)
        self.assertIn("group_indices", numeric)
        self.assertIn("next_group_indices", numeric)
        self.assertIn("all_agents_sum_rewards", numeric)
        self.assertIn("avail_actions", numeric)

    def test_get_dynamic_attrs_returns_only_edge_indices(self):
        """DYNAMIC attrs are only edge_indices and next_edge_indices."""
        dynamic = get_dynamic_attrs(self.full_profile)
        self.assertEqual(sorted(dynamic),
                         ["edge_indices", "next_edge_indices"])

    def test_get_obj_attrs_returns_only_next_avail_actions(self):
        """OBJ attr is only next_avail_actions."""
        obj = get_obj_attrs(self.full_profile)
        self.assertEqual(obj, ["next_avail_actions"])

    def test_skip_attrs_not_in_numeric_or_dynamic_or_obj(self):
        """SKIP-type attrs (e.g. infos, episode_*) are excluded."""
        numeric = set(get_numeric_attrs(self.full_profile))
        dynamic = set(get_dynamic_attrs(self.full_profile))
        obj = set(get_obj_attrs(self.full_profile))
        all_classified = numeric | dynamic | obj

        for attr in self.full_profile:
            if ATTR_REGISTRY[attr]["collate"] == CollateType.SKIP:
                self.assertNotIn(attr, all_classified,
                                 f"{attr} should be SKIP ped")

    def test_numeric_dynamic_obj_no_overlap(self):
        """No attribute appears in more than one collation category."""
        numeric = set(get_numeric_attrs(self.full_profile))
        dynamic = set(get_dynamic_attrs(self.full_profile))
        obj = set(get_obj_attrs(self.full_profile))

        self.assertEqual(len(numeric & dynamic), 0)
        self.assertEqual(len(numeric & obj), 0)
        self.assertEqual(len(dynamic & obj), 0)

    def test_all_data_attrs_have_collate_type(self):
        """Every AS_IS or DICT attr must have a non-SKIP collate type."""
        for attr, meta in ATTR_REGISTRY.items():
            if meta["storage"] in (StorageType.AS_IS, StorageType.DICT):
                self.assertIn(meta.get("collate"),
                              (CollateType.NUMERIC, CollateType.DYNAMIC,
                               CollateType.OBJ, CollateType.SKIP),
                              f"{attr} has no collate field")

    def test_collate_consistency_with_storage(self):
        """DYNAMIC attrs must be AS_IS; OBJ attrs must be DICT."""
        for attr, meta in ATTR_REGISTRY.items():
            if meta.get("collate") == CollateType.DYNAMIC:
                self.assertEqual(meta["storage"], StorageType.AS_IS,
                                 f"{attr} is DYNAMIC but not AS_IS")
            if meta.get("collate") == CollateType.OBJ:
                self.assertEqual(meta["storage"], StorageType.DICT,
                                 f"{attr} is OBJ but not DICT")


if __name__ == "__main__":
    unittest.main()
